version: '3'
tasks:
  tag:
    cmds:
      - git tag v{{.TAG}}
    vars:
      TAG:
        sh: git-conventional-commits version

  tag-push:
    cmds:
      - git push origin v{{.TAG}}
    vars:
      TAG:
        sh: git-conventional-commits version

  deploy:
    cmds:
      - task: tag
      - task: tag-push

  version:
    cmds:
      - git-conventional-commits version
  log:
    cmds:
      - git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit {{.CLI_ARGS}}

  tag-latest:
    cmds:
      - git describe --tags

  tag-all:
    cmds:
      - git fetch --all --tags # fetching remote tags
      - git tag # list tags

  build-version:
    cmds:
      - git-conventional-commits version > settings/version.txt || echo 'not installed git-conventional-commits' > settings/version.txt
  build:
    cmds:
      - task: build-version
      - mkdir -p dist
      - rm dist/* | true

      - GOOS=linux GOARCH=amd64 go build -v -o dist/autogit-linux-amd64 main.go

      # apt-cache search mingw
      # sudo apt-get install gcc-mingw-w64
      # i686-w64-mingw32-gcc-win32
      # ls /usr/bin/ | grep "mingw"
      - CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH=amd64 go build -v -o dist/autogit-windows-amd64.exe main.go
      
      # sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
      - CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 go build -v -o dist/autogit-linux-arm64 main.go

  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}

  doc-web:
    cmds:
      - godoc -http=:6060

  changelog:
    cmds:
      - git-conventional-commits changelog {{.CLI_ARGS}}

  hook:dev:
    cmds:
      - git config core.hooksPath .git-hooks-dev

  hook:prod:
    cmds:
      - git config core.hooksPath .git-hooks-prod