name: autotag

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Task
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install Autogit
      run: |
        sudo apt install -y wget
        wget https://github.com/darklab8/darklab_autogit/releases/download/v1.3.0/autogit-linux-amd64
        mv autogit-linux-amd64 /usr/local/bin/autogit
        chmod +x /usr/local/bin/autogit

    - name: Checkout repostiory with commit history!
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: future_tag
      run: echo "version=$(autogit version --newline=false --alpha --build ${{ github.run_id }})" >> $GITHUB_OUTPUT

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.future_tag.outputs.version }}",
            sha: context.sha
          })