name: autotag

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Taskfile
      uses: darklab8/infra/.github/actions/install-taskfile@master
    - name: Set up Go
      uses: darklab8/infra/.github/actions/install-go@master

    - name: Install autogit
      uses: darklab8/infra/.github/actions/install-autogit@master

    - name: Checkout repostiory with commit history!
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - id: future_tag
      run: echo "version=$(autogit semver --newline=false --alpha --build ${{ github.run_id }})" >> $GITHUB_OUTPUT

    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.future_tag.outputs.version }}",
            sha: context.sha
          })
