name: build

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:

    - name: Install Taskfile
      uses: darklab8/infra/.github/actions/install-taskfile@master

    - name: Set up Go
      uses: darklab8/infra/.github/actions/install-go@master

    - name: Install autogit
      uses: darklab8/infra/.github/actions/install-autogit@master

    - name: Checkout git repo with tags and commits for autogit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build
      run: task build

    - name: Print release changelog
      id: changelog
      run: |
        echo 'artifact<<EOF' >> $GITHUB_OUTPUT
        autogit changelog >> "$GITHUB_OUTPUT"
        echo 'EOF' >> $GITHUB_OUTPUT
    - name: upload binaries to release
      uses: softprops/action-gh-release@v2
      if: ${{startsWith(github.ref, 'refs/tags/') }}
      with:
          body: ${{ steps.changelog.outputs.artifact }}
          files: |
            dist/autogit-linux-amd64
            dist/autogit-linux-arm64
            dist/autogit-macos-amd64
            dist/autogit-macos-arm64
            dist/autogit-windows-amd64.exe
