name: Changelog

on:
  push: {}

jobs:

  validate:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout git repo with tags and commits for autogit
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: darklab8/infra/.github/actions/install-go@master
    - name: Install autogit
      uses: darklab8/infra/.github/actions/install-autogit@master
    - name: Validate changelogs
      env:
        AUTOGIT_CONFIG_VALIDATION_RULES_HEADER_SUBJECT_MIN_WORDS: "2"
      run: |
        autogit changelog --validate
